import request from '@/utils/request'

export const getGroupBuys = (params) => request({ url: '/group-buys', method: 'get', params })
export const createGroupBuy = (data) => request({ url: '/group-buys', method: 'post', data })
export const updateGroupBuy = (id, data) => request({ url: `/group-buys/${id}`, method: 'put', data })
export const deleteGroupBuy = (id) => request({ url: `/group-buys/${id}`, method: 'delete' })

export const getLimitedSaleSlots = (params) => request({ url: '/limited-sale-slots', method: 'get', params })
export const getLimitedSaleSlot = (id) => request({ url: `/limited-sale-slots/${id}`, method: 'get' })
export const createLimitedSaleSlot = (data) => request({ url: '/limited-sale-slots', method: 'post', data })
export const updateLimitedSaleSlot = (id, data) => request({ url: `/limited-sale-slots/${id}`, method: 'put', data })
export const deleteLimitedSaleSlot = (id) => request({ url: `/limited-sale-slots/${id}`, method: 'delete' })
export const getLimitedSaleItems = (slotId) => request({ url: `/limited-sale-slots/${slotId}/items`, method: 'get' })
export const createLimitedSaleItem = (slotId, data) => request({ url: `/limited-sale-slots/${slotId}/items`, method: 'post', data })
export const updateLimitedSaleItem = (id, data) => request({ url: `/limited-sale-items/${id}`, method: 'put', data })
export const deleteLimitedSaleItem = (id) => request({ url: `/limited-sale-items/${id}`, method: 'delete' })

export const getCoupons = (params) => request({ url: '/coupons', method: 'get', params })
export const createCoupon = (data) => request({ url: '/coupons', method: 'post', data })
export const updateCoupon = (id, data) => request({ url: `/coupons/${id}`, method: 'put', data })
export const deleteCoupon = (id) => request({ url: `/coupons/${id}`, method: 'delete' })
export const issueCoupon = (id, data) => request({ url: `/coupons/${id}/issue`, method: 'post', data })
export const previewCouponIssue = (id, data) => request({ url: `/coupons/${id}/issue`, method: 'post', params: { dry_run: true }, data })
export const getCouponWxacode = (id, env = 'release') => request({ url: `/coupons/${id}/wxacode`, method: 'get', params: { env } })
export const createCouponClaimTicket = (id, env = 'release') => request({ url: `/coupons/${id}/claim-tickets`, method: 'post', params: { env } })
export const getCouponAutoRules = () => request({ url: '/coupon-auto-rules', method: 'get' })
export const saveCouponAutoRules = (data) => request({ url: '/coupon-auto-rules', method: 'put', data })

export const getDepositOrders = (params) => request({ url: '/deposit-orders', method: 'get', params })
export const getDepositOrderDetail = (id, params) => request({ url: `/deposit-orders/${id}`, method: 'get', params })
export const createDepositRefund = (id, data) => request({ url: `/deposit-orders/${id}/refunds`, method: 'post', data })

export const getSlashActivities = (params) => request({ url: '/slash-activities', method: 'get', params })
export const createSlashActivity = (data) => request({ url: '/slash-activities', method: 'post', data })
export const updateSlashActivity = (id, data) => request({ url: `/slash-activities/${id}`, method: 'put', data })
export const deleteSlashActivity = (id) => request({ url: `/slash-activities/${id}`, method: 'delete' })

export const getLotteryPrizes = () => request({ url: '/lottery-prizes', method: 'get' })
export const createLotteryPrize = (data) => request({ url: '/lottery-prizes', method: 'post', data })
export const updateLotteryPrize = (id, data) => request({ url: `/lottery-prizes/${id}`, method: 'put', data })
export const deleteLotteryPrize = (id) => request({ url: `/lottery-prizes/${id}`, method: 'delete' })
export const getLotteryRecords = (params) => request({ url: '/lottery-records', method: 'get', params })
export const getLotteryClaims = (params) => request({ url: '/lottery-claims', method: 'get', params })
export const approveLotteryClaim = (id, data) => request({ url: `/lottery-claims/${id}/approve`, method: 'post', data })
export const rejectLotteryClaim = (id, data) => request({ url: `/lottery-claims/${id}/reject`, method: 'post', data })
export const shipLotteryClaim = (id, data) => request({ url: `/lottery-claims/${id}/ship`, method: 'post', data })
export const completeLotteryClaim = (id, data) => request({ url: `/lottery-claims/${id}/complete`, method: 'post', data })
export const retryLotteryFulfillment = (id) => request({ url: `/lottery-records/${id}/retry-fulfillment`, method: 'post' })

export const getActivityOptions = () => request({ url: '/activity-options', method: 'get' })
export const getFestivalConfig = () => request({ url: '/festival-config', method: 'get' })
export const updateFestivalConfig = (data) => request({ url: '/festival-config', method: 'put', data })
export const getGlobalUiConfig = () => request({ url: '/global-ui-config', method: 'get' })
export const updateGlobalUiConfig = (data) => request({ url: '/global-ui-config', method: 'put', data })
export const getActivityLinks = () => request({ url: '/activity-links', method: 'get' })
export const updateActivityLinks = (data) => request({ url: '/activity-links', method: 'put', data })

export const getSplashConfig = () => request({ url: '/splash', method: 'get' })
export const updateSplashConfig = (data) => request({ url: '/splash', method: 'put', data })
