import request from '@/utils/request'

export const getDealers = (params) => request({ url: '/dealers', method: 'get', params })
export const approveDealer = (id) => request({ url: `/dealers/${id}/approve`, method: 'put' })
export const rejectDealer = (id, data) => request({ url: `/dealers/${id}/reject`, method: 'put', data })
export const updateDealerLevel = (id, data) => request({ url: `/dealers/${id}/level`, method: 'put', data })
export const updateDealerProfile = (id, data) => request({ url: `/dealers/${id}/profile`, method: 'put', data })

export const getAdmins = (params) => request({ url: '/admins', method: 'get', params })
export const createAdmin = (data) => request({ url: '/admins', method: 'post', data })
export const updateAdmin = (id, data) => request({ url: `/admins/${id}`, method: 'put', data })
export const resetAdminPassword = (id, data) => request({ url: `/admins/${id}/password`, method: 'put', data })
export const deleteAdmin = (id) => request({ url: `/admins/${id}`, method: 'delete' })

export const getBranchAgentPolicy = () => request({ url: '/branch-agent-policy', method: 'get' })
export const updateBranchAgentPolicy = (data) => request({ url: '/branch-agent-policy', method: 'put', data })
export const getPickupStations = (params) => request({ url: '/pickup-stations', method: 'get', params })
export const getPickupStationById = (id) => request({ url: `/pickup-stations/${id}`, method: 'get' })
export const createPickupStation = (data) => request({ url: '/pickup-stations', method: 'post', data })
export const updatePickupStation = (id, data) => request({ url: `/pickup-stations/${id}`, method: 'put', data })
export const getPickupStationStaff = (id) => request({ url: `/pickup-stations/${id}/staff`, method: 'get' })
export const addPickupStationStaff = (id, data) => request({ url: `/pickup-stations/${id}/staff`, method: 'post', data })
export const removePickupStationStaff = (stationId, staffId) => request({ url: `/pickup-stations/${stationId}/staff/${staffId}`, method: 'delete' })
export const getPickupWarehouseOverview = () => request({ url: '/pickup-stations/warehouse-overview', method: 'get' })
export const getPickupStationInventory = (params) => request({ url: '/pickup-stations/inventory', method: 'get', params })
export const adjustPickupStationInventory = (id, data) => request({ url: `/pickup-stations/inventory/${id}/adjust`, method: 'post', data })
export const getPickupProcurements = (params) => request({ url: '/pickup-stations/procurements', method: 'get', params })
export const approvePickupProcurement = (id, data) => request({ url: `/pickup-stations/procurements/${id}/approve`, method: 'put', data })
export const rejectPickupProcurement = (id, data) => request({ url: `/pickup-stations/procurements/${id}/reject`, method: 'put', data })
export const receivePickupProcurement = (id, data) => request({ url: `/pickup-stations/procurements/${id}/receive`, method: 'post', data })

export const getBranchAgentStations = (params) => request({ url: '/branch-agents/stations', method: 'get', params })
export const createBranchAgentStation = (data) => request({ url: '/branch-agents/stations', method: 'post', data })
export const updateBranchAgentStation = (id, data) => request({ url: `/branch-agents/stations/${id}`, method: 'put', data })
export const deleteBranchAgentStation = (id) => request({ url: `/branch-agents/stations/${id}`, method: 'delete' })
export const getBranchAgentClaims = (params) => request({ url: '/branch-agents/claims', method: 'get', params })
export const reviewBranchAgentClaim = (id, data) => request({ url: `/branch-agents/claims/${id}/review`, method: 'put', data })

export const getUpgradeApplications = (params) => request({ url: '/upgrade-applications', method: 'get', params })
export const reviewUpgradeApplication = (id, data) => request({ url: `/upgrade-applications/${id}/review`, method: 'put', data })

export const getDirectedInvites = (params) => request({ url: '/directed-invites', method: 'get', params })
export const approveDirectedInvite = (id, data) => request({ url: `/directed-invites/${id}/approve`, method: 'post', data })
export const rejectDirectedInvite = (id, data) => request({ url: `/directed-invites/${id}/reject`, method: 'post', data })
